apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: recovery-pilot

resources:
  - namespace.yaml
  - api-deployment.yaml
  - frontend-deployment.yaml
  - network-policy.yaml
  - ingress.yaml
  - configmap.yaml

commonLabels:
  app: recovery-pilot
  managed-by: kustomize
